name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # This tells it to deploy the root of your project

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3